server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#spring:
#  ai:
#    mcp:
#      client:
#        enabled: true
#        name: my-mcp-client
#        version: 1.0.0
#        request-timeout: 30s
#        type: ASYNC  # or SYNC
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8088
#        stdio:
#          servers-configuration: classpath:/mcp-servers-config.json

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG